name: Run .NET Selenium Script

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs the workflow every 15 minutes
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x'  # Adjust to the version of .NET you're using

    - name: Restore .NET packages
      run: dotnet restore

    - name: Remove existing ChromeDriver
      run: |
        sudo rm -f /usr/local/bin/chromedriver

    - name: Add specific version of Selenium WebDriver ChromeDriver
      run: |
        dotnet add package Selenium.WebDriver.ChromeDriver --version 127.0.6533.7200

    - name: Install Google Chrome (version 127)
      run: |
        wget https://storage.googleapis.com/downloads.chromium.org/chromium-browser/chromium-browser_127.0.6533.72_amd64.deb
        sudo dpkg -i chromium-browser_127.0.6533.72_amd64.deb
        sudo apt-get -f install -y  # Fix missing dependencies

    - name: Run .NET script
      run: |
        dotnet run --project YourProject.csproj  # Replace with your .NET project file path
