name: Set Up and Run Selenium Tests

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs the workflow every 15 minutes
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Remove existing Google Chrome and ChromeDriver
      run: |
        sudo rm -f /usr/local/bin/chromedriver
        sudo apt-get remove --purge -y google-chrome-stable

    - name: Install Google Chrome (version 114)
      run: |
        wget https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.72/linux64/chrome-linux64.zip
        unzip chrome-linux64.zip -d google-chrome
        sudo mv google-chrome/chrome /usr/bin/google-chrome

    - name: Install ChromeDriver (version 114.0.5735.90)
      run: |
        wget -O /tmp/chromedriver.zip https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.72/linux64/chromedriver-linux64.zip
        unzip /tmp/chromedriver.zip -d /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      env:
        DISPLAY: :99
      run: |
        sudo Xvfb :99 -ac &
        python script.py
