name: Run Python Script with Specific Chrome and ChromeDriver

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs the workflow every 15 minutes
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Remove existing Google Chrome
      run: |
        sudo apt-get remove -y google-chrome-stable
        sudo apt-get autoremove -y

    - name: Remove existing ChromeDriver
      run: |
        sudo rm -f /usr/local/bin/chromedriver

    - name: Install Google Chrome version 114
      run: |
        # Download the specific version of Google Chrome
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb
        sudo apt-get -f install -y  # Fix missing dependencies

    - name: Install ChromeDriver version 114
      run: |
        # Download and install ChromeDriver version 114
        wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
        unzip /tmp/chromedriver.zip -d /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      env:
        DISPLAY: :99
      run: |
        sudo Xvfb :99 -ac &
        python script.py
